In [4]:
import torch

In [5]:
a = torch.ones(3) #creates a 1-D tensor, with 3 elements = 1

In [6]:
a

tensor([1., 1., 1.])

In [7]:
a[1]

tensor(1.)

In [8]:
float(a[1])

1.0

In [9]:
a[2] = 2.0

In [11]:
points  = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [12]:
points.shape #returns the size of the tensor along each dimension

torch.Size([3, 2])

In [13]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [14]:
points[:-1]

tensor([[4., 1.],
        [5., 3.]])

In [16]:
points[1:, 0]

tensor([5., 2.])

In [17]:
img_t = torch.randn(3,5,5) #randomize a 3-D tensor to rep. an image [channels, rows, columns]

In [18]:
img_t #Going to do a gray scale operation on this pretend image

tensor([[[ 0.2311, -0.5648,  1.4510,  0.0817,  0.6521],
         [ 1.0340, -0.8841, -0.1853, -0.6256,  0.1557],
         [ 1.2409,  0.7375, -0.2935,  0.2010,  0.2761],
         [-0.4670, -0.1369, -1.5420, -0.1492, -0.0528],
         [-0.6923, -0.1318,  2.5465, -0.8692,  0.1115]],

        [[ 0.4744,  0.1000, -2.0015,  1.5330, -0.2539],
         [-0.7702, -0.1202,  1.0854,  2.3698,  0.3709],
         [ 1.7170,  0.6784, -1.0531, -0.6095,  0.8780],
         [ 0.6619, -1.1325, -0.3882,  1.1156,  1.8449],
         [ 0.3957, -0.7372, -0.1209, -0.7772,  1.4620]],

        [[ 1.8854, -0.0298,  0.6059, -1.1886, -0.1295],
         [-0.0726,  1.0048,  2.7486, -2.8614, -0.3658],
         [ 0.9774,  1.4734,  0.5707,  2.4209, -0.9518],
         [ 0.4847, -1.1413,  0.8214,  0.9159,  1.6774],
         [ 1.4716, -0.3044,  0.6424,  0.0199,  0.8606]]])

In [19]:
weights = torch.tensor([.2126, .7152, .0722]) #typical weights for colors to gray-scale

In [36]:
batch_t = torch.randn(2, 3, 5, 5) #shape [ batch, channels, rows, columns] (batch = # of samples in CNN)
batch_t

tensor([[[[-1.1913, -0.4238, -0.2389,  0.6240, -0.2423],
          [-0.2585,  1.2012, -0.1477, -0.0259, -0.8374],
          [-0.3875,  0.1393,  0.0232, -0.5663,  0.4538],
          [-0.2990, -0.7492, -0.3243,  1.4963,  0.1243],
          [ 0.7621,  0.8209,  1.2936,  0.0939,  0.5314]],

         [[-1.7524, -0.8460, -1.0776,  1.2673,  0.4622],
          [-0.7882, -1.1751,  0.0309,  0.6071, -1.5326],
          [ 1.8705,  0.3437, -0.4009, -0.6207,  1.4118],
          [-1.0742,  0.6929, -1.4886, -0.9399,  1.4520],
          [ 2.1534,  0.2852,  0.1541, -1.0691, -0.4026]],

         [[-0.7827,  0.0851,  1.2279, -0.9361,  0.0432],
          [ 1.1040, -2.4619,  0.8498,  0.0804, -0.0322],
          [-0.4668,  0.6177, -0.0523, -0.8248, -0.4563],
          [ 0.6435, -0.5546, -0.9019,  1.1295, -0.4871],
          [-0.9095, -0.2502,  0.8673,  0.2260,  0.0635]]],


        [[[-0.0327,  0.3964, -0.3040, -1.6834,  0.2518],
          [ 0.0982,  3.0025, -0.1698,  0.2657, -0.7968],
          [-1.3685, -1.

In [21]:
#find unweighted means

In [22]:
img_gray_naive = img_t.mean(-3)

In [26]:
img_gray_naive #dimension that is averaged is reduced

tensor([[ 8.6366e-01, -1.6488e-01,  1.8447e-02,  1.4201e-01,  8.9588e-02],
        [ 6.3735e-02,  1.7933e-04,  1.2163e+00, -3.7239e-01,  5.3598e-02],
        [ 1.3118e+00,  9.6309e-01, -2.5864e-01,  6.7080e-01,  6.7431e-02],
        [ 2.2653e-01, -8.0357e-01, -3.6957e-01,  6.2743e-01,  1.1565e+00],
        [ 3.9168e-01, -3.9115e-01,  1.0227e+00, -5.4216e-01,  8.1135e-01]])

In [27]:
batch_gray_naive = batch_t.mean(-3)

In [28]:
batch_gray_naive

tensor([[[ 0.2222, -0.4043,  0.1918,  0.3448, -0.1908],
         [ 0.0105,  0.1389,  0.1906,  0.2511,  0.6440],
         [-0.0163,  0.3174, -0.8774, -0.0171,  0.3230],
         [-0.8098,  0.0055,  0.3726,  1.0297, -0.0661],
         [ 0.4821, -0.5608,  0.2436,  0.2273,  0.8575]],

        [[ 0.2359,  0.0477, -0.4360,  0.3114, -0.2479],
         [-0.9193, -0.5521,  0.1219,  0.3002,  1.2946],
         [-1.1939,  0.6218,  0.0042,  0.7718,  0.5895],
         [ 0.0878, -0.4120, -0.1931,  0.9453, -0.6639],
         [ 0.3743, -0.1028,  0.4058, -0.7099, -0.4617]]])

In [29]:
#Can multiple tensors that are the same shape, as well as shapes that have size 1 in a given dimension.

In [30]:
#unsqueezing means we append a dimension w/ size 1, this is so product retains shape

In [31]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)

In [32]:
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [33]:
img_weights = (img_t *unsqueezed_weights)

In [34]:
img_weights

tensor([[[ 4.9129e-02, -1.2008e-01,  3.0847e-01,  1.7362e-02,  1.3864e-01],
         [ 2.1983e-01, -1.8796e-01, -3.9386e-02, -1.3301e-01,  3.3092e-02],
         [ 2.6383e-01,  1.5678e-01, -6.2403e-02,  4.2730e-02,  5.8695e-02],
         [-9.9290e-02, -2.9115e-02, -3.2782e-01, -3.1725e-02, -1.1215e-02],
         [-1.4718e-01, -2.8026e-02,  5.4139e-01, -1.8480e-01,  2.3705e-02]],

        [[ 3.3932e-01,  7.1526e-02, -1.4315e+00,  1.0964e+00, -1.8158e-01],
         [-5.5084e-01, -8.5961e-02,  7.7631e-01,  1.6949e+00,  2.6526e-01],
         [ 1.2280e+00,  4.8518e-01, -7.5315e-01, -4.3591e-01,  6.2794e-01],
         [ 4.7337e-01, -8.0993e-01, -2.7761e-01,  7.9791e-01,  1.3195e+00],
         [ 2.8303e-01, -5.2727e-01, -8.6453e-02, -5.5584e-01,  1.0456e+00]],

        [[ 1.3613e-01, -2.1540e-03,  4.3748e-02, -8.5818e-02, -9.3487e-03],
         [-5.2409e-03,  7.2548e-02,  1.9845e-01, -2.0659e-01, -2.6407e-02],
         [ 7.0569e-02,  1.0638e-01,  4.1202e-02,  1.7479e-01, -6.8719e-02],
        

In [37]:
batch_weights = (batch_t * unsqueezed_weights)

In [38]:
batch_weights

tensor([[[[-0.2533, -0.0901, -0.0508,  0.1327, -0.0515],
          [-0.0550,  0.2554, -0.0314, -0.0055, -0.1780],
          [-0.0824,  0.0296,  0.0049, -0.1204,  0.0965],
          [-0.0636, -0.1593, -0.0690,  0.3181,  0.0264],
          [ 0.1620,  0.1745,  0.2750,  0.0200,  0.1130]],

         [[-1.2533, -0.6051, -0.7707,  0.9064,  0.3306],
          [-0.5637, -0.8404,  0.0221,  0.4342, -1.0961],
          [ 1.3378,  0.2458, -0.2868, -0.4439,  1.0097],
          [-0.7683,  0.4956, -1.0646, -0.6722,  1.0385],
          [ 1.5401,  0.2040,  0.1102, -0.7647, -0.2879]],

         [[-0.0565,  0.0061,  0.0887, -0.0676,  0.0031],
          [ 0.0797, -0.1777,  0.0614,  0.0058, -0.0023],
          [-0.0337,  0.0446, -0.0038, -0.0596, -0.0329],
          [ 0.0465, -0.0400, -0.0651,  0.0816, -0.0352],
          [-0.0657, -0.0181,  0.0626,  0.0163,  0.0046]]],


        [[[-0.0070,  0.0843, -0.0646, -0.3579,  0.0535],
          [ 0.0209,  0.6383, -0.0361,  0.0565, -0.1694],
          [-0.2910, -0.

In [39]:
img_gray_weighted = img_weights.sum(-3)

In [40]:
batch_gray_weighted = batch_weights.sum(-3)

In [41]:
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [42]:
#^^ all this matrix multiplications may be hard to keep up-> we can name dimensions as well

In [44]:
img_t.shape

torch.Size([3, 5, 5])

In [45]:
# ... adding this we can leave out any number of dimensions

In [46]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')

C:\Users\Kalbang\anaconda3\lib\site-packages\torch\_tensor.py:780: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return super(Tensor, self).refine_names(names)


In [48]:
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')

In [49]:
print("img_namedL", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img_namedL torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [50]:
#values of tensors are allocated in contiguous chunks of memory by torch.storage unlike Python lists

In [51]:
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [54]:
#even though tensor is 2-D, storage is a contiguous array of 6 elements( always 1 dimensional)

In [55]:
points_storage = points.storage()
points_storage[4]

2.0

In [56]:
#element in storage is based off offset, stride, and size

In [57]:
#accesing element(i,j) =  offset + stride[0] *i + stride[1] * j

In [58]:
###########################

In [59]:
#Every tensor can be moved to GPU

In [60]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

In [61]:
points_gpu = points.to(device='cuda')

In [62]:
####################

In [63]:
#Saving a tensor object to a pickle file

In [64]:
torch.save(points, '../data/ourpoints.t')

In [65]:
list(range(9))

[0, 1, 2, 3, 4, 5, 6, 7, 8]